
# https://medium.com/geekculture/custom-slack-notification-with-circleci-workflow-9f42d9b767d2

version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
 

jobs:
  build:
  
    steps:
  
      - checkout
      - run:
          name: Set template variables
          command: |
            echo "export ZAP_ARTIFACT_URL = https://www.google.com" >> $BASH_ENV
            echo ${ZAP_ARTIFACT_URL}
