version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
          ignore-redirects: true
          additional-options: -r cli,junit,json  

    
      - run:
          name: Save Test Result
          command: |
            echo "***my artifact files ***" 
            mkdir -p api/test-results/newman
            cp ./newman/newman-run-report-*.xml api/test-results/newman
            cp ./newman/newman-run-report-*.json api/test-results/newman
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_BUILD_NUM}
            echo $(ls api/test-results/newman/newman-run-report-*.json)
         
      
      - store_artifacts:
          path: api/test-results/newman
          
      - run:
          name: Set template variables
          command: |
           echo "export API_ARTIFACT_URL=https://${CIRCLE_BUILD_NUM}-404629133-gh.circle-artifacts.com/0/$(ls api/test-results/newman/newman-run-report-*.json)" >> $BASH_ENV
            echo  ${API_ARTIFACT_URL}
           
      - slack/notify:
          channel: test-reports
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                   "text": {
                    "type": "plain_text",
                    "text": "API test completed :ballot_box_with_check:",
                    "emoji": true
                   }
                },
                 {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Test*: https://gateway-ocr.openrm.dev\n"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://cdn-icons-png.flaticon.com/512/603/603197.png",
                    "alt_text": "Postman"
                  }
                },
                {
                    "type": "divider"
                 },
                 
                 
                 {
                  "type": "actions",
                  "elements": [
                  
                   {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Full Report"
                      },
                      "style": "primary",
                      "url": "${API_ARTIFACT_URL}"
                    },
                    
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "style": "primary",
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
                
                    
              ]
            }
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 4" # At 03:00 on every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: slack
  manual:
    jobs:
      - build:
          context: slack
      
   
