version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    #working_directory: ~/repo
   # docker:
   #   - image: circleci/node:10.16.3
    
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
          ignore-redirects: true
          additional-options: -r cli,junit,json,htmlextra  
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
     
      - run:
          name: Install Dependencies
          command: npm install
   
      - run:
          name: Generate Report
          command: npm run report

      - run:
          name: Save Test Result
          command: |
            echo "***my artifact files ***" 
            mkdir -p api/test-results/newman
            cp ./newman/newman-run-report-*.xml api/test-results/newman
            cp ./newman/newman-run-report-*.json api/test-results/newman
            cp ./newman/newman-run-report-*.html api/test-results/newman


      - store_artifacts:
          path: api/test-results/newman

      
      

      
