version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4
 
commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
  
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
          ignore-redirects: true
          additional-options: -r cli,junit,json              
           
      - run:
          name: Save Test Result
          command: |
            echo "***my artifact files ***" 
            mkdir -p api/test-results/newman
            cp ./newman/newman-run-report-*.xml api/test-results/newman
            cp ./newman/newman-run-report-*.json api/test-results/newman
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_BUILD_NUM}
       
         
      - store_test_results:
          path: api/test-results
          
      - store_artifacts:
          path: api/test-results/newman
          
      - notify_slack_error
      - notify_slack_pass
          
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 4" # At 03:00 on Thursday https://crontab.guru/
          filters:
            branches:
              only:
                - main
    jobs:
      - build

  manual:
    jobs:
      - build
