version: 2.1

orbs:
    hello: circleci/hello-build@0.0.5

workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
 

#jobs:
 # build:
  #    steps:
   #   - checkout
    #  - run:
     #     name: Set template variables
      #    command: |
       #     echo "export ZAP_ARTIFACT_URL = https://www.google.com" >> $BASH_ENV
        #    echo ${ZAP_ARTIFACT_URL}
