version: 2.1
orbs:
  slack: circleci/slack@4.4.4

jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: cache clean
          command: npm cache clean --force

      - run:
          name: Generate Report
          command: |
              newman run ForestApp_api_collection.json \
              --env-var "testToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjY2LCJvcmdhbml6YXRpb25JZCI6MjYwLCJlbWFpbCI6ImZhaXNhbEBvcGVucm0uY28uanAiLCJmb3JnZWRCeSI6InRvc2hpcm9Ab3BlbnJtLmNvLmpwIiwicm9sZXMiOlsic3lzVGVzdGVyIl0sImlhdCI6MTYyNjkyNjgxMSwiZXhwIjoxNjMyOTYwMDAwLCJpc3MiOiJvcGVucm9vbSJ9.2QbjMZqLVJ5IP_W-CT9Jp3m1IIclj-VzCSEGShq9IkJMF4nmPtG7ytO56jv3Ds9tDJrAxwAsMQmDqIFxGURiUIXEdZ2wk404zuQToL1doOP2VqfAikIVI-iMdaGtKVxYZgJIGPWJ3GLraRDFr587rBwYpSXPb5HDQMf_9t7AkvmzZlI6f_gYB0k2_npXhRouhFfgLdg5MW-G5-irgSiKxPJ_26DAG3wJYvghRKPLEucIaotF4_KMIIcLA5AwrooKGhK0qSkkEm7-1wghALCtXhdSiYAgHuSKTy0I7kvHaWoJxWqL__FrfZMuzwn6msjd1nUILoDvpFVW-Sn6mF64SA" \
              --ignore-redirects \
              --reporters htmlextra,json,junit \
              
      - run:
          name: Download jq
          command: curl -sLo jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq

      - run:
          name: Save Test Reports
          command: |
            echo "*** my artifact reports ***"
            mkdir -p api/test-results/newman
            cp ./newman/newman-run-report-*.xml api/test-results/newman
            cp ./newman/newman-run-report-*.json api/test-results/newman
            cp ./newman/ForestApp-*.html api/test-results/newman
      - store_test_results:
          path: api/test-results

      - store_artifacts:
          path: api/test-results/newman

      - run:
          name: Set template variables
          command: |
            export REPORT_JSON=$(ls api/test-results/newman/newman-run-report-*.json)
            echo "export POSTMAN_TOTAL=$(cat $REPORT_JSON | jq .run.stats.assertions.total)" >> $BASH_ENV
            echo "export POSTMAN_FAILED=$(cat $REPORT_JSON | jq .run.stats.assertions.failed)" >> $BASH_ENV
      - slack/notify:
          channel: Cicleci
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*API Test Completed* $(if [ \"$CCI_STATUS\" = \"pass\" ]; then echo :ballot_box_with_check:; else echo :warning:; fi)"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Test:* https://gateway-ocr.openrm.dev\n*Branch:* ${CIRCLE_BRANCH}\n*Running Job:* ${CIRCLE_JOB}\n*Job Parallelism:* ${CIRCLE_NODE_TOTAL}\n*Result:* ${CCI_STATUS}\n*Assertions:* total=${POSTMAN_TOTAL} failed=${POSTMAN_FAILED}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://cdn-icons-png.flaticon.com/512/603/603197.png",
                    "alt_text": "Postman"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Full Report"
                      },
                      "style": "primary",
                      "url": "https://${CIRCLE_BUILD_NUM}-404629133-gh.circle-artifacts.com/0/$(ls api/test-results/newman/ForestApp-*.html)"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "View Job"
                      },
                      "style": "danger",
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1-5" # At 04:00 on every weekday from Monday through Friday.
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
          context: slack

  manual:
    jobs:
      - test:
          context: slack
