version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
 
  
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
     
      - run:
          name: Download jq
          #command: curl -sLo /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/local/bin/jq
          echo "***F**"
     
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
       
           
 
