version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
          ignore-redirects: true
          additional-options: -r cli,junit
        
      - run:
          name: Save Test Result
          command: |
            echo "my artifact file ***" 
            mkdir -p ~/test-results/newman
            cp ./newman/newman-run-report-*.xml ~/test-results/newman
         
      - store_artifacts:
          path: ~/test-results
        
      - store_artifacts:
          path: ~/test-results/newman
          
