version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    #working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
     
      - run:
          name: Install Dependencies
          command: npm install
   
      - run:
          name: Generate Report
          command: npm run report

      - store_artifacts:
          path: api/test-results/newman

      
