
version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
 
  
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
     
      - run:
          name: MY ECO MESSAGE
          command: |
            echo "***my artifact files ***" 
            echo "Hello ${CIRCLE_USERNAME}"
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
            
     
    
    

           
 
