version: '2.1'
orbs:
  slack: circleci/slack@4.4.4
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: circleci
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                   "text": {
                    "type": "plain_text",
                    "text": "API test completed :ballot_box_with_check:",
                    "emoji": true
                   }
                },
                 {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Test*: https://gateway-ocr.openrm.dev\n"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://cdn-icons-png.flaticon.com/512/603/603197.png",
                    "alt_text": "Postman"
                  }
                },
                {
                    "type": "divider"
                 },
                    
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack
