
# https://medium.com/geekculture/custom-slack-notification-with-circleci-workflow-9f42d9b767d2

version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
 
commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: circleci

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
          channel: circleci
  
  
  trigger_slack_notification:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*THIS IS A TEXT NOTIFICCATION SLACK 2*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
          channel: circleci
  
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - run: apk update && apk add curl curl-dev
      - run:
          name: Download jq
          command: curl -sLo /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/local/bin/jq
      - trigger_slack_notification
      - checkout
      - newman/newman-run:
          collection: ./test/postman_collection.json
          ignore-redirects: true
          additional-options: -r cli,junit,json              
           
  #    - run:
   #       name: Save Test Result
   #       command: |
    #        echo "***my artifact files ***" 
     #       mkdir -p api/test-results/newman
      #      cp ./newman/newman-run-report-*.xml api/test-results/newman
       #     cp ./newman/newman-run-report-*.json api/test-results/newman
        #    echo ${CIRCLE_BRANCH}
         #   echo ${CIRCLE_BUILD_NUM}
     
         
  #    - store_test_results:
   #       path: api/test-results
          
   #   - store_artifacts:
    #      path: api/test-results/newman
         

         
      - notify_slack_error
      - notify_slack_pass
          
