version: 2.1
orbs:
  slack: circleci/slack@4.4.4
 
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout                        
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            
      - run:
          name: cache clean
          command: npm cache clean --force     
      - run:
          name: Generate Report
          command: npm run-script report  #package.json
       
      - run:
          name: Download jq
          command: curl -sLo jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq
     
      - run:
          name: Save Test Result
          command: |
            echo "***my artifact files ***" 
            mkdir -p api/test-results/newman
            cp ./newman/newman-run-report-*.xml api/test-results/newman
            cp ./newman/newman-run-report-*.json api/test-results/newman
            cp ./newman/API_Configuration-*.html api/test-results/newman
            
      - store_test_results:
          path: api/test-results
          
      - store_artifacts:
          path: api/test-results/newman
          
          
      - slack/notify:
          channel: circleci
          event: always
          custom: |
            {
             	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "*API Test Completed* :ballot_box_with_check:"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "*Test:* https://gateway-ocr.openrm.dev\n*BRANCH:* ${CIRCLE_BRANCH}\n*RUNNING JOB:* ${CIRCLE_JOB}\n*JOB PARALLELISM:* ${CIRCLE_NODE_TOTAL}"
            			},
            			"accessory": {
            				"type": "image",
            				"image_url": "https://cdn-icons-png.flaticon.com/512/603/603197.png",
            				"alt_text": "Postman"
            			}
            		},
            		{
            			"type": "divider"
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"emoji": true,
            						"text": "View Full Report"
            					},
            					"style": "primary",
            					"url": "https://${CIRCLE_BUILD_NUM}-405850638-gh.circle-artifacts.com/0/$(ls api/test-results/newman/API_Configuration-*.html)"
            				},
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"emoji": true,
            						"text": "View Job"
            					},
            					"style": "danger",
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }
         
          

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 4" # At 04:00 on every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: slack

  manual:
    jobs:
      - build:
          context: slack
  
          

      
