version: 2.1
orbs:
  newman: postman/newman@0.0.2
  slack: circleci/slack@4.4.4
 
  
jobs:
  build:
    docker:
    - image: circleci/buildpack-deps:curl-browsers
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
    - run:
        command: echo "Hello ${CIRCLE_USERNAME}"
        command: echo "Hello ${DOCKERHUB_PASSWORD}"
      - run:
          name: MY ECO MESSAGE
          command: |
            echo "***my artifact files ***" 
     
  
           
 
