version: '2.1'
orbs:
  slack: circleci/slack@4.4.4
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: circleci
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "API test completed :ballot_box_with_check:",
                    "emoji": true
                  }
                }
                    
              ]
            }
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack
